import type { Metadata } from "next";
import { Geist, Geist_Mono, Inknut_Antiqua, VT323 } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const vt = VT323({
  variable: "--font-vt323",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inknut = Inknut_Antiqua({
  variable: "--font-inknut",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "TermYnal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${vt.variable} ${geistMono.variable} ${inknut.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
